# Generated by Django 2.1.7 on 2019-03-05 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField()),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='articles',
            table='article',
        ),
        migrations.AddField(
            model_name='comments',
            name='comments_articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Articles'),
        ),
    ]
